push.rules.rpart<-function(object,prefix='')
{
  require(RODBC)
  rules<-rules.table.rpart(crs$rpart)
  rules$Rule<-paste(prefix,rules$Rule,sep='.')
  rules$Subrule<-paste(prefix,rules$Subrule,sep='.')
  sqlSave(xj,rules,tablename="AUTHCLASS_RULES",append=TRUE,rownames=FALSE)
  subrules<-subrule.table.rpart(crs$rpart)
  subrules$Subrule<-paste(prefix,subrules$Subrule,sep='.')
  sqlSave(xj,subrules,tablename="AUTHCLASS_SUBRULES",append=TRUE,rownames=FALSE)
}